### ISSUE TITLE
Liste des dépendances

### ISSUE THREAD

**Issue by Spriithy** [AlexMog/SurvivalMMO#1]
Yo!

Ca serait pas mal de mettre un README avec une liste des dépendances, de quoi track ce qui est implémenté etc :) Histoire de pouvoir trifouiller dans le code pour ceux que ca intéresserait.

- Google JSON ([lien](https://github.com/google/gson))
- Google GUAVA ([lien](https://github.com/google/guava/tree/master/guava))
- Netty io ([lien](http://netty.io/))

A voir après, si tu veux que des gens puisse bidouiller etc. Mais vu que tu le fait en stream et tout, ca pourrait en aider plus d'un :)

**Comment by Spriithy** [comment]
J'ajoute aussi Artemis ([lien](https://github.com/junkdog/artemis-odb)) à la liste ! (et donc guava / gradle)

**Comment by Slaynash** [comment]
Les dépendances sont gérées par Maven, dans le fichier pom.xml normalement

**Comment by Spriithy** [comment]
Ah ouais joli
