### ISSUE TITLE
READ ME, MYSELF AND I?

### ISSUE THREAD

**Issue by GuillaumeBouchetEpitech** [AlexMog/SurvivalMMO#2]
Hi,

Un fichier README sympa en Francais avec les links des differents trucs? (GDoc, votes, etc.)

Bisous <3

**Comment by Slaynash** [comment]
J'ai une partie des liens ici: http://smlls.ddns.net/alexidees/
Mais sinon le readme est effectivement manquant :/

**Comment by AlexMog** [comment]
Comme je l'ai dis durant l'un de mes lives, un Readme sera mis en place soonTM. Il n'est juste pas prioritaire pour l'instant.
Si néanmoins vous désirez en créer un vous mêmes, n'hésitez pas à fork le repo et proposer une pull request :) c'est le but de github après tout :D
