### ISSUE TITLE
Quel langage pour le client ?

### ISSUE THREAD

**Issue by Laygendev** [AlexMog/SurvivalMMO#3]
Salut,

En quel langage doit être codé le client ?

Je vois du LUA dans le dossier scripts, faut-il s'orienter vers du LUA avec Love2D ? ^^

Merci

**Comment by AlexMog** [comment]
N'importe quel langage est adapté pour le client! 
Il suffit juste de respecter le protocole de communication entre le client et le serveur :)
La documentation du protocole est disponible ici: https://docs.google.com/spreadsheets/d/1-N3FmyBLQ8Q9hNm3yS3SUmvdAkhHIDtg95r81A0sZn0/edit?usp=sharing
Les packets sont envoyés en WebSocket pour simplifier le développement d'un client Web si l'envie te prend :)
Les configurations WebSockets peuvent être trouvées ici: https://github.com/AlexMog/SurvivalMMO/blob/master/src/main/java/survivalgame/server/network/NetworkManager.java#L83
Et tu pourra trouver la définition de tous les packets ici: 
https://github.com/AlexMog/SurvivalMMO/tree/master/src/main/java/survivalgame/server/network/packet
Ainsi que l'encodeur de packets ici: https://github.com/AlexMog/SurvivalMMO/blob/master/src/main/java/survivalgame/server/network/PacketEncoder.java
Et le décodeur de packets ici: https://github.com/AlexMog/SurvivalMMO/blob/master/src/main/java/survivalgame/server/network/PacketDecoder.java

J'essayerai de retravailler dessus dès que j'aurai le temps pour ajouter des features supplémentaires, mais pour l'instant, je pense qu'il est possible de tester le bouzin pour voir si il marche !

A bientôt !

**Comment by Laygendev** [comment]
D'accord, je pense faire un client en vanilla JS. 

Pour le déplacement des personnages, c'est du case par case ? Ce n'est pas précisé sur le doc.

PS: je ne savais pas si je devais ouvrir une autre issue.

**Comment by AlexMog** [comment]
Le déplacement du personnage est bien case par case, mais en prenant en compte le temps de trajet ofc :) (il ne se téléporte pas).

**Comment by Laygendev** [comment]
Ofc :)

Donc pathfinding.

Merci je clos cette issue
